apiVersion: app.redislabs.com/v1alpha1
kind: RedisEnterpriseCluster
metadata:
  name: "redis-enterprise"
spec:
  # Add fields here
  nodes: 1
  persistentSpec:
    enabled: true
    storageClassName: "standard"
    volumeSize: 20Gi
